spring.application.name=notification-service

server.servlet.context-path=/notifications
server.port=9040

spring.datasource.url=jdbc:postgresql://localhost:5432/notificationdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka